---
- name: Desplegar Nginx personalizado
  hosts: mis_nodos
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Asegurar que Nginx est√© iniciado y habilitado
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Desplegar el index.html personalizado desde la plantilla
      template:
        src: templates/index.html.j2      # Origen en tu PC
        dest: /var/www/html/index.html    # Destino en los contenedores
        mode: '0644'                      # Permisos de lectura para todos
